# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: adad2440769269a770c7ed1efe5c284cb14d2c7c8b101b0bc96010f44555633438091ea8775dbf557a1f45d2a81d264c869692bacfa825d722fa57e18d2368ca

test:
  secret_key_base: 0822e77fe0920e2ae81e70bb99692819cdb294b9f5dfb9ef3d92f79cda1d888a614512a0f20ad969bba136dd90165c3ff08862da2342fb047a2f839f482c4498

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
